
substitutions:
  _IMAGE_NAME:  'watermarker'


steps:

  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest', '.' ]


  - name: 'gcr.io/cloud-builders/docker'
    id: push
    args: ['push', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest', '.' ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: deploy
    entrypoint: gcloud
    args: 
      - run
      - deploy
      - $_IMAGE_NAME
      - --image=gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest
      - --platform=managed
      - --region=asia-south1

